name: Test run
on:
  - push

jobs:
  base64:
    name: Recover With Base64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          MY_CLIENT_ID: ${{ secrets.NPM_LIBRARY_TOKEN }}
        run: |
          echo "MY_CLIENT_ID (****)    = ${MY_CLIENT_ID}"
          echo "MY_CLIENT_ID (base64) = $(echo ${MY_CLIENT_ID} | base64)"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE | base64 -D"
